### PR TITLE
Updated netty & maven-release-plugin version

### PR DESCRIPTION
**Pull request by iggydv**
Updated netty version. This commit includes some changes to the `AlternativeCompositeByteBuf`, most of which I left unimplemented for simplicity sake - For now It is all I need to continue

### CODE REVIEW

**Comment by iggydv** [comment]
All I really want to do is create a patch for the current latest version, seeing as there are some mayor updates in the next release - Also, I need this desperately for a project I am working on, if anyone can take a look at this I'll be extremely grateful @tbocek @stsmedia @amuelli @vershinin

**Comment by tbocek** [comment]
Can you create a pull request that I can merge?

**Comment by iggydv** [comment]
I will target the PR on master then - thanks for checking in, also is it at all possible to create a patch for latest release with this change as well?

**Comment by tbocek** [comment]
Hmm, I think it might be better to target 5.0-beta8, as master is currently in a unstable state. Probably its a good idea to continue with 5.0-beta8 in master and branch the current master.

**Comment by iggydv** [comment]
That would be ideal, actually also a better branching strategy :)

**Comment by iggydv** [comment]
@tbocek will you be able to create the `release-development` branch and reset the HEAD to the last stable commit or the last release commit?
I am unable to do that, so hopefully you can do this :)

**Pull request closed without merging**
