### PR TITLE
Tomp2p parent 5.0 beta8.1

### PR DESCRIPTION
**Pull request by iggydv**
Upgraded Netty and maven-release-plugin versions.
_Take note:_
`AlternativeCompositeByteBuf` now contains a lot of unimplemented methods, seeing as the `ByteBug` interface changed. The only methods that were updated were the methods required to allow the project to compile.

I'm pretty sure we'll need to update these methods soon, as these unimplemented methods might cause unexpected behavior

### CODE REVIEW

**Comment by tbocek** [comment]
thx!

**Comment by iggydv** [comment]
@tbocek I'm unable to do a patch release, I do not have permissions to do the release.
`Tomp2p-parent-5.0-beta8.1` was the versioning I had in mid, but I'm not sure if that goes against your current versioning strategy. 

Regardless, would you be able to push the artifact to the tomp2p repository?

**Comment by tbocek** [comment]
Deployd, its not visible in the HTML, but its in the repo: https://tomp2p.net/dev/mvn/net/tomp2p/tomp2p-core/5.0-Beta8.1/tomp2p-core-5.0-Beta8.1.jar

**Comment by iggydv** [comment]
Fantastic! My pipeline is now finally green :D

**Pull request merged**
